@startuml Пример C4: Контекст
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Система управления автопарком - Контекстная диаграмма

Person(Водитель, "Водитель", "Просматривает свое расписание, маршруты, сообщает о происшествиях или изменениях в плане")
Person(Технический_персонал, "Технический персонал", "Учет и планирование технического обслуживания автомобилей")
Person(Администратор, "Администратор", "управление доступом к системе, настройки, отчеты")
Person(Диспетчер, "Диспетчер", "Планирует маршруты, создает расписания для водителей, мониторит движения автомобилей")

System(система_управления_автопарком, "Система управления автопарком", "Обеспечивает полный цикл от работами с заказами: создание, просмотр, завершения, модерация")

System_Ext(верификатор_документов, "Верификатор документов", "Внешняя служба проверка подлинности докуметнов")
System_Ext(онлайн_карты, "Онлайн карты", "Внешняя служба для мониторинга движения автомобилей")

Rel(Технический_персонал, система_управления_автопарком, "", "HTTPS")
Rel(Водитель, система_управления_автопарком, "", "HTTPS")
Rel(Диспетчер, система_управления_автопарком, "", "HTTPS")
Rel(Администратор, система_управления_автопарком, "", "HTTPS")
Rel(система_управления_автопарком, верификатор_документов, "Передает документы для пороверки", "API/HTTPS")
Rel(система_управления_автопарком, онлайн_карты, "Запрашивает текущее местоположение автомобиля", "API/HTTPS")

@enduml